# Generated by Django 5.0.2 on 2024-03-03 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_user_address_line1_user_city_user_profile_picture_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='address_line1',
            new_name='address',
        ),
        migrations.AddField(
            model_name='user',
            name='pincode',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
